GET http://localhost:8000/units

###

GET http://localhost:8000/units/67accf2a14f8d7277d62640c

###

POST http://localhost:8000/units
Content-Type: application/json

{
    "name": "Scouts",
    "faction": "Space Marine"
}


###


DELETE http://localhost:8000/units/67accf2a14f8d7277d62640c


###


PATCH http://localhost:8000/units/67accf2a14f8d7277d62640c
Content-Type: application/json

{
    "name": "Deathwing Knights",
    "class": "Dark Angel"
}
